databases:
  - name: vegiteam
    databaseName: vegiteam
    user: vegiteam

services:
  - type: web
    name: vegiteam
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vegiteam
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4