# Generated by Django 4.2.3 on 2023-07-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="share",
            name="form_name",
            field=models.CharField(max_length=20),
        ),
    ]
